# Generated by Django 5.0.2 on 2024-02-21 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Destination_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Source_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('travel_class', models.CharField(choices=[('Premium', 'Premium'), ('Economy', 'Economy')], max_length=10)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.passenger')),
                ('Destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.destination_city')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.source_city')),
            ],
        ),
    ]
