# Generated by Django 5.0.2 on 2024-02-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_booking_destination_alter_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='testapp.airport'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger',
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='testapp.airport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ManyToManyField(to='testapp.passenger'),
        ),
    ]
